# Generated by Django 2.2.24 on 2021-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0002_remove_plananual_unspsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='plananual',
            name='unspc',
            field=models.BigIntegerField(null=True),
        ),
    ]
