# Generated by Django 2.2.24 on 2021-08-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0003_plananual_unspc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plananual',
            name='fecha_radicacion',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plananual',
            name='fechadecdp',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plananual',
            name='fechadegiros',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plananual',
            name='fechadesolicituddecdp',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plananual',
            name='fechaestimadacompra',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plananual',
            name='fechaestimadapago',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plananual',
            name='fechaestimadaproceso',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
    ]
