# Generated by Django 2.2.24 on 2021-08-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0004_auto_20210827_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plananual',
            name='descripcionobjeto',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='plananual',
            name='objetodelcontrato',
            field=models.CharField(max_length=1024),
        ),
    ]
