# Generated by Django 2.2.24 on 2021-08-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0005_auto_20210827_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plananual',
            name='objetodelcontrato',
            field=models.CharField(max_length=2048),
        ),
    ]
