# Generated by Django 2.2.24 on 2021-08-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0006_auto_20210827_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plananual',
            name='códigorubropresupuestal',
            field=models.CharField(max_length=240),
        ),
    ]
