# Generated by Django 2.2.24 on 2021-08-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0007_auto_20210827_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plananual',
            name='objetodelcontrato',
            field=models.CharField(max_length=4096),
        ),
    ]
