# Generated by Django 2.2.24 on 2021-08-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0008_auto_20210827_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plananual',
            name='objetodelcontrato',
            field=models.TextField(),
        ),
    ]
