# Generated by Django 2.2.24 on 2021-08-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0009_auto_20210827_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plananual',
            name='descripcionobjeto',
            field=models.TextField(),
        ),
    ]
