# Generated by Django 2.2.24 on 2021-08-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0011_auto_20210827_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plananual',
            name='nombrerubroprespupuestal',
            field=models.TextField(),
        ),
    ]
