# Generated by Django 2.2.24 on 2021-08-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0012_auto_20210827_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='tipoidcontratista',
            field=models.CharField(max_length=10),
        ),
    ]
