# Generated by Django 2.2.24 on 2021-08-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0013_auto_20210827_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='objeto',
            field=models.TextField(),
        ),
    ]
