# Generated by Django 2.2.2 on 2021-03-23 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('estructura', '0002_load_initial_data'),
    ]

    def create_estado(apps, schema_editor):
        from apps.estructura.models import Estado, Modulo
        from apps.autenticacion.models import Modulos
        from apps.contratacion.models import ProcesoEstados

        modulo = Modulo.objects.get(nombre=Modulos.ALISTAMIENTO)

        if not Estado.objects.filter(nombre=ProcesoEstados.SUBSANACION).exists():
            superuser = Estado.objects.create(
                nombre=ProcesoEstados.SUBSANACION,
                modulo=modulo, )
            superuser.save()

    operations = [
        migrations.RunPython(create_estado),
    ]
