# Generated by Django 2.2.24 on 2021-08-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0003_estado_subsanar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeDesarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
            ],
        ),
        migrations.DeleteModel(
            name='ValidacionEstado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='plan_de_desarrollo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.PlanDeDesarrollo'),
        ),
    ]
