# Generated by Django 2.2.19 on 2021-08-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0004_auto_20210806_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandedesarrollo',
            options={'verbose_name': 'Plan De Desarrollo', 'verbose_name_plural': 'Planes De Desarrollo'},
        ),
    ]
