# Generated by Django 2.2.19 on 2021-09-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_auto_20210826_0006'),
        ('estructura', '0005_auto_20210902_1829'),
    ]

    operations = [
    ]
