# Generated by Django 2.2.2 on 2021-02-16 13:41

import apps.contratacion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('nombre', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=32)),
                ('logs', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_radicacion', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('id_cupo', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('numero_de_proceso', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('nombre_contratista', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('cedula_contratista', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('plazo', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('numero_cdp', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('valor_cdp', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('valor_contrato', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('numero_contrato', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('objeto', models.TextField(blank=True, default=None, max_length=2048, null=True)),
                ('numero_crp', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('valor_crp', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('nombre_supervisor', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('caso_seven', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('vigencia', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('fecha_inicio', models.DateField(blank=True, default=None, null=True)),
                ('fecha_final', models.DateField(blank=True, default=None, null=True)),
                ('dependencia_contratista', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Dependencia')),
                ('estado', models.ForeignKey(default=apps.contratacion.models.ProcesoEstados('REVISION'), on_delete=django.db.models.deletion.CASCADE, to='estructura.Estado', to_field='nombre')),
                ('proyecto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Proyecto')),
                ('tipologia_especifica', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.TipologiaEspecifica')),
            ],
            options={
                'ordering': ['fecha_radicacion'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionEstadoProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validate_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacion.Proceso')),
                ('validacion_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.ValidacionEstado')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosProcesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estructura.Estado')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacion.Proceso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignacion Usuario-Procesos',
                'verbose_name_plural': 'Asignaciones de usuarios y procesos',
            },
        ),
        migrations.AddField(
            model_name='proceso',
            name='usuarios',
            field=models.ManyToManyField(through='contratacion.UsuariosProcesos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proceso',
            name='validaciones',
            field=models.ManyToManyField(blank=True, through='contratacion.ValidacionEstadoProceso', to='estructura.ValidacionEstado'),
        ),
        migrations.CreateModel(
            name='EstadoNovedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novedad', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacion.Proceso')),
            ],
            options={
                'verbose_name': 'Novedad de Cambio de estado',
                'verbose_name_plural': 'Novedades de cambio de estado',
            },
        ),
        migrations.CreateModel(
            name='ProcesosSinAsignar',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contratacion.proceso',),
        ),
    ]
