# Generated by Django 2.2.2 on 2021-03-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0003_asignacion_procesos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcesosSinAsignar',
        ),
    ]
