# Generated by Django 2.2.24 on 2021-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0006_remove_usuariosprocesos_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosprocesos',
            name='novedad',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
