# Generated by Django 2.2.24 on 2021-07-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0007_usuariosprocesos_novedad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosprocesos',
            options={'ordering': ('-date',), 'verbose_name': 'Asignacion Usuario-Procesos', 'verbose_name_plural': 'Asignaciones de usuarios y procesos'},
        ),
    ]
