# Generated by Django 2.2.24 on 2021-07-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0008_auto_20210701_1910'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariosprocesos',
            unique_together=set(),
        ),
    ]
