# Generated by Django 2.2.24 on 2021-09-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0011_auto_20210902_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='modificacion',
            field=models.CharField(blank=True, default='CONTRATO_INICIAL', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='modificacion',
            name='modificacion',
            field=models.CharField(choices=[('CONTRATO INICIAL', 'CONTRATO_INICIAL'), ('OTROSI', 'OTROSI'), ('ADICION', 'ADICION'), ('CESION', 'CESION'), ('PRORROGA', 'PRORROGA'), ('SUSPENSION', 'SUSPENSION'), ('REINICIO', 'REINICIO'), ('ADICION_PRORROGA', 'ADICION_PRORROGA'), ('TERMINACION_ANTICIPADA', 'TERMINACION_ANTICIPADA')], default='CONTRATO_INICIAL', max_length=300),
        ),
    ]
