# Generated by Django 2.2.24 on 2021-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0012_auto_20210905_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='numero_de_proceso',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
