# Generated by Django 2.2.24 on 2021-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0013_auto_20210905_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificacion',
            name='Cedente',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='Cesionario',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='DocumentoCedente',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='DocumentoCesionario',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='FechaFin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='FechaInicio',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='FechaReinicio',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='Valor',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
