# Generated by Django 2.2.24 on 2021-09-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0014_auto_20210905_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='procesoraiz',
        ),
        migrations.DeleteModel(
            name='ProcesoRaiz',
        ),
    ]
