# Generated by Django 2.2.24 on 2021-09-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0016_modificacion_cdp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modificacion',
            old_name='Cedente',
            new_name='cedente',
        ),
        migrations.RenameField(
            model_name='modificacion',
            old_name='Cesionario',
            new_name='cesionario',
        ),
        migrations.RenameField(
            model_name='modificacion',
            old_name='DocumentoCedente',
            new_name='documentoCedente',
        ),
        migrations.RenameField(
            model_name='modificacion',
            old_name='DocumentoCesionario',
            new_name='documentoCesionario',
        ),
        migrations.RenameField(
            model_name='modificacion',
            old_name='FechaFin',
            new_name='fechaFin',
        ),
        migrations.RenameField(
            model_name='modificacion',
            old_name='FechaInicio',
            new_name='fechaInicio',
        ),
        migrations.RenameField(
            model_name='modificacion',
            old_name='FechaReinicio',
            new_name='fechaReinicio',
        ),
        migrations.RenameField(
            model_name='modificacion',
            old_name='Valor',
            new_name='valor',
        ),
    ]
