# Generated by Django 2.2.24 on 2021-09-08 02:43

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0017_auto_20210907_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='estado_devolucion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='estado_devolucion', to='estructura.Estado', to_field='nombre'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='modificacion',
            field=models.CharField(blank=True, default='CONTRATO_INICIAL', max_length=30, null=True),
        ),
    ]
