# Generated by Django 2.2.24 on 2021-12-03 22:28

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0006_merge_20210928_0009'),
        ('contratacion', '0018_auto_20210907_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificacion',
            name='modificacion',
            field=models.CharField(choices=[('CONTRATO INICIAL', 'CONTRATO_INICIAL'), ('OTROSI', 'OTROSI'), ('ADICION', 'ADICION'), ('CESION', 'CESION'), ('PRORROGA', 'PRORROGA'), ('SUSPENSION', 'SUSPENSION'), ('REINICIO', 'REINICIO'), ('ADICION_PRORROGA', 'ADICION_PRORROGA'), ('ADICION_PRORROGA_OTROSI', 'ADICION_PRORROGA_OTROSI'), ('ADICION_PRORROGA_SUSPENSION', 'ADICION_PRORROGA_SUSPENSION'), ('TERMINACION_ANTICIPADA', 'TERMINACION_ANTICIPADA')], default='CONTRATO_INICIAL', max_length=300),
        ),
    ]
