# Generated by Django 2.2.2 on 2021-02-16 13:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):
        from apps.autenticacion.models import USUARIO

        superuser = USUARIO.objects.create_superuser(
            username='admin',
            email='admin@admin.com',
            password='Houston, we have a problem')

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
