# Generated by Django 2.2.24 on 2021-08-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_super_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadosdeusuarios',
            options={'verbose_name': 'Estado de usuarios', 'verbose_name_plural': 'Estados de usuarios'},
        ),
    ]
